### ISSUE TITLE
Table options on the left broken by #100

### ISSUE THREAD

**Issue by CGDogan** [btovis/btovis.github.io#105]
I make a table. The table doesn't update anymore when I update column list on the left since #100 

If I update a column name then change filter options above, then it refreshes correctly. so a refresh is missing somewhere

**Comment by Hex27** [comment]
I tested this on the main branch and on #107, and the table is working correctly. Are you pressing the right boxes?

**Comment by CGDogan** [comment]
#111 fixed it for me
