### ISSUE TITLE
sidebar and filterer to agree on default filters for new files

### ISSUE THREAD

**Issue by CGDogan** [btovis/btovis.github.io#115]
DataFilterer, when a new file is added, ticks all new checkboxes.

Sidebar, when a new file is added, ticks all new checkboxes only if all checboxes had been ticked - otherwise deselects new checkboxes.

Currently, adding one of the files, disabling the warning checkbox, adding the other, causes showing data with the new warning despite the new checkbox being unticked

CC @Hex27 we can discuss this later

**Comment by Hex27** [comment]
I just took at look at this, shouldn't recalculateFilteredData inside DataFilterer take care of this? DataFilterer and the sidebar inputoption both contain the correct filter

**Comment by CGDogan** [comment]
it does; it assumes "accept" for all non-previously-existing possibilities which is why it diverges from what the sidebar does

**Comment by Hex27** [comment]
> it does take care of it; it assumes "accept" for all non-previously-existing possibilities which is why it diverges from what the sidebar does

But that’s not what containing a class filter with only one accept entry should mean isn’t it? Even if I change it from the panel’s side, the filter being stored is going to be wrong

**Comment by CGDogan** [comment]
So should I change my code to precisely:

- If all accept, accept all new
- Even if one reject, reject all new

Is this what your code does? All I need to do is to make my code consistent with yours therefore I'd like to know if my understanding is correct. Or do you do a proportion less than 50% or something like that in your code? Could you please point me to your code that decides whether or not accept new things, if the behavior isn't precisely one of those I've mentioned?

**Comment by Hex27** [comment]
The code in Selector just copies the same filter from the template variable in the constructor

It isn’t able to detect what the new additions are to set defaults for them short of iterating the whole set again

But I don’t see why this is about accepting or rejecting by default, the filter class in memory only allows one set element, so why doesn’t recalculatefilters just reapply the same filter?

**Comment by Hex27** [comment]
#143
