### ISSUE TITLE
Not everything updated on unload file

### ISSUE THREAD

**Issue by cshuenss** [btovis/btovis.github.io#118]
Clicking the x to remove the last file in global options panel doesn't clear a panel if it's the last one (do we even want to delete a panel if there is no data for it?)

Also, the warnings list is persistent if a different file with different warnings is loaded after the first file is unloaded

**Comment by cshuenss** [comment]
I don't think we bother fixing this, but just wanted to make it known

**Comment by Hex27** [comment]
The first one is a large bug with dataFilterer, it's not being updated

**Comment by CGDogan** [comment]
I'm aware of the second one, I'm currently working on it, I'm sorry for the confusion I should have opened an issue that this was never implemented
