### ISSUE TITLE
On file upload; disable file uploads. On deleting a file; first make it impossible to upload and disable other delete buttons

### ISSUE THREAD

**Issue by CGDogan** [btovis/btovis.github.io#124]
JS is a single threaded language and database should be accessed from one thread only.

On adding a file, the drag-drop container can set its property (a new property) say `isBusy`. Ondrop handler should check isBusy, if true, do window.alert("Cannot upload a file while uploading another"). otherwise, set isBusy, process as usual then reset isBusy.

On deleting a file, between the start and end of delete processing, all delete buttons should be disabled and isBusy of the ondrop container should be set.

**Comment by Hex27** [comment]
Weirdly, when trying to reproduce a race condition, it just didn't let me do it. The browser blocks during the file processing and doesn't let me introduce another file.

This seems to be already impossible
