### ISSUE TITLE
Update Date range shown

### ISSUE THREAD

**Issue by CGDogan** [btovis/btovis.github.io#132]
Leonard your code does a good job extending the range if previous range was max then a new file is added beyond the range so the range grows. Apparently the code needs to send this change to the visual datepicker UI so it doesn't show "from 2023/08/20 to 2023/08/20" but instead changes correctly to "from 2023/08/20 to 2023/08/23" etc.

[csv1.csv](https://github.com/btovis/btovis.github.io/files/14410165/csv1.csv)
[csv2.csv](https://github.com/btovis/btovis.github.io/files/14410166/csv2.csv)

**Comment by Hex27** [comment]
#143
