### ISSUE TITLE
Data Filterer does not work as expected

### ISSUE THREAD

**Issue by George-Ogden** [btovis/btovis.github.io#134]
I've added tests to the `data-filter` branch in 83c802d and they are all failing. Am I interfacing incorrectly with the code or is this a bug?

**Comment by CGDogan** [comment]
I'll fix the tests now unless you would like to do it?

**Comment by George-Ogden** [comment]
I will fix and merge this shortly

**Comment by CGDogan** [comment]
Proven to be a bug so my fault
