### ISSUE TITLE
Create grouping by time range

### ISSUE THREAD

**Issue by George-Ogden** [btovis/btovis.github.io#138]
Allow data to be grouped by time range
I propose doing this with an additional column/structure that stores the group/group-index.
When plotting, we can aggregate by this additional column

**Comment by CGDogan** [comment]
Are you sure you would like to do this? A better way would be, instead of adding a new column, sorting datas on adding, this way the partition size and partition count would be configurable

**Comment by Hex27** [comment]
That way would cause every widget has to sort and add the column, why not do it at the panel level?

**Comment by CGDogan** [comment]
If the original data is kept sorted, the filtered data will always be sorted

**Comment by George-Ogden** [comment]
> If the original data is kept sorted, the filtered data will always be sorted

What about time of day?
