### ISSUE TITLE
Delete file and readd it, make sure it works

### ISSUE THREAD

**Issue by CGDogan** [btovis/btovis.github.io#142]

**Comment by CGDogan** [comment]
@Hex27 I tried again and couldn't reproduce it, could you please name/upload if not large the csvs and tell me the exact order of uploading them and deleting them?

**Comment by Hex27** [comment]
1. Upload 1 CSV
2. Add debug widget
3. Filter by probability >= 1 
4. Add CSV2
5. Delete CSV2
6. Add CSV2 <--- triggers

**Comment by Hex27** [comment]
This is solved on my branch
