### ISSUE TITLE
Maybe add a circle under "time range"

### ISSUE THREAD

**Issue by CGDogan** [btovis/btovis.github.io#146]

**Comment by CGDogan** [comment]
@Hex27 I found how to do this. Basically searching for "how to make pie chart in css" then doing the same thing. Would you mind if I implement this?

**Comment by Hex27** [comment]
Sure, but be sure to fix the high priority stuff first

**Comment by CGDogan** [comment]
sorry, exporting csvs would have been a high priority and not this if I would do one thing
