### ISSUE TITLE
forbid any computations on render(), add a refresh() method to widgets

### ISSUE THREAD

**Issue by CGDogan** [btovis/btovis.github.io#157]
Render() asks a widget to give the displayed result HTML. This is called very often, such as even, when the user changes option in a different widget. We should add a refresh function that is called when Data or Filtered Data has updated. This should calculate result HTML as `output: JSElement[]` so render() should only return this and don't do anything else. This means that when render() is called, the cached result will be used

@Hex27 You certainly know React better than me, what do you think?

A good small example could be the TableWidget

**Comment by Hex27** [comment]
It may be more productive to identify what's calling refresh and see if its unnecessary
