### ISSUE TITLE
UI Tweaks

### ISSUE THREAD

**Issue by George-Ogden** [btovis/btovis.github.io#173]
Here's a list of UI changes to complete:
- [x] [Correct titles on charts](#174)
- [x] [Display correct x axis on bar chart](#174 )
- [x] Get rid of checkboxes on option menu
- [x] Add text entry to probability box
- [x] #205
Feel free to edit/add

**Comment by cshuenss** [comment]
which checkboxes on which option menu?

**Comment by George-Ogden** [comment]
> which checkboxes on which option menu?

![image](https://github.com/btovis/btovis.github.io/assets/38294960/d6e76750-77b6-4c54-bb48-616887498942)

**Comment by George-Ogden** [comment]
@cshuenss like #189 - can you extend that to the other inputs, please?

**Comment by Hex27** [comment]
#246 sorted out the checkboxes for species selector and location
