### ISSUE TITLE
Widgets re-render unnecessarily when a new widget is added or deleted

### ISSUE THREAD

**Issue by Hex27** [btovis/btovis.github.io#190]

**Comment by Hex27** [comment]
Just took a crack at this, I have no idea how to solve this

**Comment by Hex27** [comment]
Just for completeness, I tried:

- Widget UUID keys in WidgetComp, and in PanelComp
- Widget list from panel as useState in PanelComp
- export default React.memo(WidgetComp)

And different combinations of the above

Didn't stop the debug widget from rendering everytime a widget was added or removed

**Comment by CGDogan** [comment]
This is a hard issue perhaps you (assuming you have time, I doubt it, there are likely other important issues) could wrap each widget in a react component caching render() for latest filtering uuid and widget options or you could rewrite each render() to first return empty element then refresh itself after computing the html result in async (which only reduces lag and doesn't fix the problem)

Apparently the reason react arrays have "key" is to remove the need to rerender elements when they didnt change

**Comment by Hex27** [comment]
Oh I’ve tried that, the promise refused to run asynchronously.

I’ve also tried unifying widgetcomp keys to the widget uuid, but they still rerendered everytime

**Comment by Hex27** [comment]
React.memo and widget uuid keys were implemented in #223. They don't fix this specific issue, but they do isolate calls into widget.render
