### ISSUE TITLE
things to ask & final todos

### ISSUE THREAD

**Issue by CGDogan** [btovis/btovis.github.io#192]
survey date or actual date?

when no survey date, leave it empty or copy from actual date

Final todos: ~~#167 provide instructions for mapbox api key~~

Check licenses up to date

ask for which license for this project

**Comment by Hex27** [comment]
I think its related to project information, so leave it empty.

**Comment by Hex27** [comment]
No more mapbox api key needed

**Comment by Hex27** [comment]
Settled #307
