### ISSUE TITLE
Chart grouping: prevent the user from choosing options with too many unique values

### ISSUE THREAD

**Issue by CGDogan** [btovis/btovis.github.io#200]
Where in the code does it get stuck @George-Ogden

**Comment by George-Ogden** [comment]
I will have a look

**Comment by George-Ogden** [comment]
@CGDogan what do you mean? I am struggling to reproduce this

**Comment by CGDogan** [comment]
Open Task Manager on your computer and monitor your browser's RAM usage:

Upload 150MB file german_ultrasonic_example.csv

 Add bar chart

Time group by file

**Comment by CGDogan** [comment]
How about greying out options with more than 10000 unique values? The mouse hover can say "there are too many unique values of this"
