### ISSUE TITLE
Guard table column selectors against heavy queries

### ISSUE THREAD

**Issue by Hex27** [btovis/btovis.github.io#214]
> In my own investigation, its because of keyFromRow inside the table widget. That method constructs a unique key that can be used for indexing by the search bar, but it becomes terrible as the key becomes long (i.e. concatinating many many columns)

> Additionally, cases which try to get nearly as many rows as the original csv (i.e. filter by only probability) tend to cause issues too (i.e. rows like probability or recording file name)

> I'm speculating that the search bar is causing this, because it was much faster when I commented it out, but it's also a very important feature for it

Warn users against clicking heavy columns

**Comment by CGDogan** [comment]
*make it impossible. You could disable search in those columns if there are over 5,000 set elements for that set
