### ISSUE TITLE
The sidebar shrinks horizontally when an accordion opens past 100% height

### ISSUE THREAD

**Issue by Hex27** [btovis/btovis.github.io#228]
![image](https://github.com/btovis/btovis.github.io/assets/9026032/34ccd5ec-7aaa-4b41-b0f3-6568254346a2)
![image](https://github.com/btovis/btovis.github.io/assets/9026032/d8a7687b-8609-4c2c-870a-75925c60f788)

**Comment by cshuenss** [comment]
Is this an issue? What UI thing does it noticeably break? (to recreate open in chrome)

**Comment by Hex27** [comment]
More of a minor view thing because the width changes and some stuff will calculate pixel widths (like the map, because of plotly) and have minor side effects depending on screen width

**Comment by Hex27** [comment]
No visible artifacts
