### ISSUE TITLE
Data error when you delete a normal csv after adding a bird csv

### ISSUE THREAD

**Issue by Hex27** [btovis/btovis.github.io#231]
[NJ3353_Cairnty.csv](https://github.com/btovis/btovis.github.io/files/14466383/NJ3353_Cairnty.csv)
[testdata2.csv](https://github.com/btovis/btovis.github.io/files/14466406/testdata2.csv)
Upload Cairnty, then testdata2.
Delete testdata2. This creates a stack trace that looks like this:
`Uncaught TypeError: Cannot read properties of undefined (reading 'value')
    at ReferenceSet.addRef (ReferenceSet.ts:32:25)
    at Data.remakeSets (Data.ts:161:32)
    at Data.removeCSV (Data.ts:127:14)
    at PageManager.removeCSV (PageManager.ts:48:19)`

**Comment by CGDogan** [comment]
ok thanks for the report certainly the fault is in my code

**Comment by Hex27** [comment]
How's progress on this? Is it a very tricky problem?

**Comment by CGDogan** [comment]
There's no large problem in code, the fix is ready but it will wait for some new tests against some similar problems unless you need the fix urgently?

**Comment by CGDogan** [comment]
opened pr
