### ISSUE TITLE
UI Tweaks

### ISSUE THREAD

**Issue by George-Ogden** [btovis/btovis.github.io#265]
- [x] Make widget height appropriate for panel
- [x] Get rid of scroll bar on table widget
- [x] Improve formatting of arrows on scroll bar
- [x] Sort out colours + spacing
- [x] Resize widget headings
- [x] Change colours of new widget icons
- [x] Sort out new panel button
- [x] Convert to bootstrap

**Comment by Hex27** [comment]
Is this closed?

**Comment by George-Ogden** [comment]
I am working on it now
