### ISSUE TITLE
We have just broken css

### ISSUE THREAD

**Issue by CGDogan** [btovis/btovis.github.io#267]
@George-Ogden I don't think this black background of the button is intentional:

![Screenshot 2024-03-03 at 13 00 53](https://github.com/btovis/btovis.github.io/assets/126820728/cced6be5-3606-43db-a2c6-3e7c4f146830)

**Comment by Hex27** [comment]
It looks like all the bootstrap button css broke. I'll take a look at it

**Comment by Hex27** [comment]
Looks like the new css file dictated that all buttons will have a black background by default. The new css also makes a square button that isn't bootstrap, so now half the buttons aren't bootstrap. Is this intentional? @George-Ogden

**Comment by George-Ogden** [comment]
Sorry - it's not. I didn't notice it because I was in dark theme

**Comment by Hex27** [comment]
It does look like we didn't mark some buttons with the bootstrap "btn" class, so it's just defaulting to the App.css button styling. Do we want to use bootstrap classes for all the buttons, or shall I just mark the border-radius 8 as !important and commit that fix?

**Comment by George-Ogden** [comment]
Can you try removing this line:
```css
    background-color: #1a1a1a;
```
App.css:420

**Comment by George-Ogden** [comment]
Let's use bootstrap classes as they'll work on all browsers

**Comment by Hex27** [comment]
#268 ready for PR
