### ISSUE TITLE
date and time selector buttons do nothing

### ISSUE THREAD

**Issue by cshuenss** [btovis/btovis.github.io#288]
In the panel options, the date range and time range selector buttons do nothing when clicked. One can still type in the time/date desired, but cannot select it using a popup UI because none appears

**Comment by Hex27** [comment]
@George-Ogden This was caused by the onBlur=refreshWidgets inside InputOption, by right the widgets refresh upon an option change, so inside callback, after/before panel.refreshComponent.

I've fixed it on my branch, I'm going to check for other refreshing problems before pushing

**Comment by George-Ogden** [comment]
I think it also applies to the map
