### ISSUE TITLE
Graphs should default to top X many items

### ISSUE THREAD

**Issue by CGDogan** [btovis/btovis.github.io#291]
I uploaded the CSV 6 times to simulate lots of rows and our program is responsive enough but the graphs, because they are trying to show too many items, are slow, so I propose a "mutually exclusive selector" as a widget option to show top 10 items or show all items. Sorting and finding top 10 can be done after categorization and it'll be much faster if it defaults to this option rather than having the user to wait a long time then to disable species

**Comment by Hex27** [comment]
What is the sorting criteria? Top 10 of what?

**Comment by CGDogan** [comment]
The item selected under count grouping. Total count.

And I just noticed that the list of items on the right of the graph isn't sorted. This seems to be very important to be useful. The top item most be the most popular item in the graph etc.

**Comment by Hex27** [comment]
But the common species might be the expected ones and the uncommon ones might be the important ones, that would bias against rare occurrences, which was one of the core targets of the visualisation (spotting outliers/unusual trends)

**Comment by Hex27** [comment]
Let's refrain from big features at this stage
