### ISSUE TITLE
Make the sidebar fill the entire height

### ISSUE THREAD

**Issue by Hex27** [btovis/btovis.github.io#42]
![image](https://github.com/btovis/btovis.github.io/assets/9026032/7f74cff4-c04c-44c8-b8e6-0f8d1b4cf84b)

**Comment by George-Ogden** [comment]
I've done some things with CSS before so should be able to fix it to full height.

**Comment by George-Ogden** [comment]
Has someone already done this? It doesn't seem to be an issue for me
![image](https://github.com/btovis/btovis.github.io/assets/38294960/f2756200-0345-4ebe-976b-3314dcc23b90)

**Comment by Hex27** [comment]
The child elements probably need to overflow the sidebar for it to happen. I will add that my computer is zoomed more than normal though
