### ISSUE TITLE
Data oddities

### ISSUE THREAD

**Issue by Hex27** [btovis/btovis.github.io#78]
Here's a list of data oddities that may need to be handled in future:

- No ID can appear under SPECIES

**Comment by CGDogan** [comment]
https://github.com/btovis/btovis.github.io/pull/75/files#diff-5d44a0512404c4cb35d342b536f9870f304ae1abd709c62c74f5b9b36442a4efR49 fixes this? I noticed that clicking on New Table Widget without any files uploaded crashed the website so I added this catch there
