### ISSUE TITLE
fix delete button buried due to overflow

### ISSUE THREAD

**Issue by CGDogan** [btovis/btovis.github.io#82]
assignee: me

**Comment by cshuenss** [comment]
Do elaborate - which delete button? The panel delete button in sidebar? If so, then that was fixed in #81 (unless if it's still broken for you...)

**Comment by cshuenss** [comment]
(although tbf could make it clearer that it is scrollable, could fix that too)

**Comment by CGDogan** [comment]
I upload a CSV, add a table widget, I click on delete panel button, now, due to overflow, a user can't confirm delete. You are right to have changed it to overflow, now we need to fix dialog appearing

**Comment by cshuenss** [comment]
so #71, or something different?

**Comment by CGDogan** [comment]
No, only since #81 it's sometimes impossible for the user to click on delete. Nevertheless your pull request only exposed your problem and did not introduce it

**Comment by CGDogan** [comment]
I have now opened a pull request but I'm no expert either. Moving it from sidebar to app.tsx seems to allow it to go on top of everything
