### ISSUE TITLE
Table: show rows with empty cells or not?

### ISSUE THREAD

**Issue by CGDogan** [btovis/btovis.github.io#91]
Considering, for example the default table with Species, Warnings, and row count. The current behaviour is that the filterer skips if any of the cells are empty. This doesn't fit the usecase that "Please list for me all the species; along with their warnings" Most likely, the user didn't mean "Please list for me all the species with non-null warnings, along with their warnings". As Leonard points out, this results in a lots of rows with blanks. How can this be solved? "Show only data with all three cells nonempty?" Add a checkbox next to each option: "show non-null only?"

**Comment by Hex27** [comment]
Fill empty cells with something

**Comment by CGDogan** [comment]
That might be a good idea, then it needs to be fixed with https://github.com/btovis/btovis.github.io/issues/149 and filled when the file is first added. With <empty> or SetElement("<Empty>") or ??:??:?? I propose. You can assign that to me.

Nevertheless, after this, shouldn't we give an option to the user to just look at the cleanest data by checking a "show rows with all cells nonempty only"? Or would you prefer the user should open every accordion on the left and uncheck <empty> for that column specifically, for each column. What do you think? I'm just suggesting we could give the user the option "no ill data please!" because maybe the user will be interested in the clean data only without spending time checking each column but this might discourage BTO from fixing it.

You can have the final say on this

**Comment by Hex27** [comment]
I think we can add that in the table's options, sounds like a good option to have
